In [5]:
import numpy as np

# Introduction to numerical algorithms
## Practice class 4 - Solving systems of linear equations, Gauss elimination

### System of linear equations

The general form is:
$$\begin{cases}
a_{11} x_1 + a_{12} x_2 +\dots + a_{1n} x_n = b_1 \\
a_{21} x_1 + a_{22} x_2  + \dots + a_{2n} x_n = b_2 \\ 
\vdots\\
a_{m1} x_1 + a_{m2} x_2 + \dots + a_{mn} x_n = b_m,
\end{cases}$$
where $x_1, x_2,\dots,x_n$ are the unknowns, $a_{11},a_{12},\dots,a_{mn}$ are the coefficients of the system, and $b_1,b_2,\dots,b_m$ are the constant terms.

### In matrix form
$$A\mathbf{x}=\mathbf{b},$$
where
$$A=
\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{pmatrix},\quad
\mathbf{x}=
\begin{pmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{pmatrix},\quad
\mathbf{b}=
\begin{pmatrix}
b_1 \\
b_2 \\
\vdots \\
b_m
\end{pmatrix}.$$

### Gauss elimination

First we create a matrix $(A|b)$. Then we try to make the value below the diagonal zero, and the diagonal one. 

Allowed steps:
* Swapping two rows,
* Multiplying a row by a nonzero number,
* Adding a multiple of one row to another row.

Example:

$$\begin{pmatrix}
1 & 3 & 1 & 9 \\
1 & 1 & -1 & 1 \\
3 & 11 & 5 & 35
\end{pmatrix}\to
\begin{pmatrix}
1 & 3 & 1 & 9 \\
0 & -2 & -2 & -8 \\
0 & 2 & 2 & 8
\end{pmatrix}\to
\begin{pmatrix}
1 & 3 & 1 & 9 \\
0 & -2 & -2 & -8 \\
0 & 0 & 0 & 0
\end{pmatrix}\to
\begin{pmatrix}
1 & 0 & -2 & -3 \\
0 & 1 & 1 & 4 \\
0 & 0 & 0 & 0
\end{pmatrix}$$

The steps:
1. The <b>first</b> row times $-1$ is added to the second row, and the $-3$ times the <b>first</b> row is added to the third row
2. The <b>second</b> row is added to the third row resulting in a row with only zeros, which is a singular case.
3. The <b>second</b> row is multiplied by $-2$ and it is added to the first row multiplied by $-3$. 

##  Warmup
As a warmup we will program the allowed steps of the Gauss elimination and we will perform the previous manipulation

In [6]:
A = np.array([[1,3,1],[1,1,-1],[3,11,5]],dtype=float)
b = np.array([9,1,35],dtype=float)
B = np.column_stack((A,b))
print(B)

[[ 1.  3.  1.  9.]
 [ 1.  1. -1.  1.]
 [ 3. 11.  5. 35.]]


### Warmup Task 1
Write the row swapping algorithm! 

In [7]:
def GE_swap(B,i,j):
    #Write your code here
    tmp = np.copy(B[i])
    B[i] = np.copy(B[j])
    B[j] = tmp
    #Do it in a way that it modifies B itself

In [8]:
# Test your code here!
B = np.column_stack((A,b))
print(B)
GE_swap(B,1,2)
print(B)

[[ 1.  3.  1.  9.]
 [ 1.  1. -1.  1.]
 [ 3. 11.  5. 35.]]
[[ 1.  3.  1.  9.]
 [ 3. 11.  5. 35.]
 [ 1.  1. -1.  1.]]


### Warmup Task 2
Write a function that multiplies a row of `B` by a non-zero `alpha` number.

In [9]:
def GE_multiply(B,i,alpha):
    #Write your code here
    B[i] = B[i] * alpha
    #Do it in a way that it modifies B itself

In [10]:
# Test your code here!
B = np.column_stack((A,b))
print(B)
GE_multiply(B,1,0.4)
print(B)

[[ 1.  3.  1.  9.]
 [ 1.  1. -1.  1.]
 [ 3. 11.  5. 35.]]
[[ 1.   3.   1.   9. ]
 [ 0.4  0.4 -0.4  0.4]
 [ 3.  11.   5.  35. ]]


### Warmup Task 3
Write a function that adds `alpha` times row `j` to row `i`.

In [11]:
def GE_add_multiply(B,i,j,alpha):
    #Write your code here
    B[i] = B[i] + B[j] * alpha
    #Do it in a way that it modifies B itself

In [12]:
# Test your code here!
B = np.column_stack((A,b))
print(B)
GE_add_multiply(B,1,2,-2)
print(B)

[[ 1.  3.  1.  9.]
 [ 1.  1. -1.  1.]
 [ 3. 11.  5. 35.]]
[[  1.   3.   1.   9.]
 [ -5. -21. -11. -69.]
 [  3.  11.   5.  35.]]


### Warmup Task 4
Apply the following steps to your matrix:
1. The <b>first</b> row times $-1$ is added to the second row, and the $-3$ times the <b>first</b> row is added to the third row
2. The <b>second</b> row is added to the third row resulting in a row with only zeros, which is a singular case.
3. The <b>second</b> row is multiplied by $-2$ and it is added to the first row multiplied by $-3$. 

In [13]:
#Here we recreated B so you can start work with the original matrix here
B = np.column_stack((A,b))
print(B)

[[ 1.  3.  1.  9.]
 [ 1.  1. -1.  1.]
 [ 3. 11.  5. 35.]]


In [14]:
#Do your work here
#Step 1
GE_add_multiply(B, 1, 0, -1)
GE_add_multiply(B, 2, 0, -3)
#step 2
B[2] += B[1]
#Step 3
GE_multiply(B, 0, -3)
GE_add_multiply(B, 0, 1, -2)

#Check!!!
print(B) # <-- Is it the matrix we had above? 

[[ -3.  -5.   1. -11.]
 [  0.  -2.  -2.  -8.]
 [  0.   0.   0.   0.]]


### Task 1 - Gauss eleimination
First we will write the simplest case of a Gauss elimination.
1. Construct $B=(A|b)$, and get the number of rows.
2. Loop over all the columns.
3. Check for singularity of the diagonal is zero. If the matrix singular raise an exception, if not swap rows if necessery and continue the elimination.
4. Make the diagonal element one.
5. Loop over the elements below the diagonal and eliminate each element.
6. Contruct the solution based on the following:

Solution is
$$x_i=b_i-\sum_{j=i+1}^{N}b_ix_i$$
If the vector of solution at the beginning is zero $\mathbf{x}=(x_1,x_2,x_3)=(0,0,0)$, then we can rewrite it as:
$$x_i=b_i-\mathbf{b}\mathbf{x},$$
provided we go with $i$ in the reverse order.

In [19]:
def my_GE(A, b):
    """Solves the equation A*x=b."""

    B = np.column_stack((A, b)).astype(float)
    N = len(B)

    for i in range(N - 1):
        pivot_values = np.abs(B[i:, i])
        j = i + int(np.argmax(pivot_values))

        if pivot_values[j - i] == 0:
            raise np.linalg.LinAlgError("No pivot available in this column.")

        if i != j:
            GE_swap(B, i, j)

        GE_multiply(B, i, 1.0 / B[i, i])

        for row in range(i + 1, N):
            GE_add_multiply(B, row, i, -B[row, i])

    if B[N - 1, N - 1] == 0:
        raise np.linalg.LinAlgError("No pivot available in the final row.")

    x = np.zeros(N)
    for i in range(N - 1, -1, -1):
        x[i] = (
            B[i, N] - np.dot(B[i, i + 1:N], x[i + 1:N])
        ) / B[i, i]

    return x

### Test your code!
1. **Try to solve the original equation!**

Recover the result that it is a singular matrix.

2. **Now try with the following equation, for which you should have a solution!**
$$\begin{gather}
3x_1−x_2+4x_3=2\\
17x_1+2x_2+x_3=14\\
x_1+12x_2−7x_3=54
\end{gather}$$

In [20]:
A = np.array([[3,17,1],[-1,2,12],[4,1,-7]],dtype=float)
b = np.array([2, 14, 54],dtype=float)
my_GE(A, b)


array([20.55081967, -3.7147541 ,  3.49836066])

### Task 2 - Partial pivoting
In this task we follow with a more sophisticated way to do the Gauss elimination. One can face problems with the previous implementation by the accumulation of floating point errors. To minimalize this error we will utizile that we can change the order of equations and we will choose the largest absolute value element from blow the diagonal to eliminate with called the pivot element.

Your task is to implement the selection of the pivot element by the modification of point 3. in the previous task. Look for the maximum absolute value element below the diagonal, including the diagonal itself. Perform a row change if the maximal element if not the diagonal. What will be the condition for singularity in terms of the maximal absolute value?

In [17]:
def my_GE_partial_pivot(A,b):

_IncompleteInputError: incomplete input (4182245213.py, line 1)

### Task 3 - Full pivoting
You can realize that you have the freedom to choose a pivot element not only from the column below the diagonal but from the whole submatrix below the diagonal. 

Your task is to further modify you previous function to perform the full pivoting.
1. Write the column swap function that swaps columns `i` and `j` in `B`
2. Select the pivot element from the submatrix and store the index of it. 
3. If necessery perform the row and the column swap.
4. Note that with column swaps you change the order of the variables, you need to track it, so create a variable where you track these changes.
5. After constructing the solution by backward substitution reconstruct the original order of the variables!

In [ ]:
def my_GE_full_pivot(A,b):

### Task 4 - Compare the different methods

There are two set of equations below where you can test the efficiency of the different methods. 

In [ ]:
A = np.array([
    [1e-20, 1.0, 1.0],
    [1.0,   1.0, 2.0],
    [1.0,   2.0, 3.0]
])

b = np.array([
    2.0,
    4.0,
    6.0
])
# solution ~[0,0,2]

In [ ]:
A = np.array([
    [ 1.82018118e-08,  1.59970044e+00,  1.16352866e+00],
    [-4.60125295e-08,  4.60403044e-07,  1.42871095e-07],
    [ 7.13592793e-08, -1.63108794e+01,  1.19484660e-04]
], dtype=np.float32)

b = np.array([
     6.68998686e+00,
     1.30340684e-06,
    -3.26214003e+01
], dtype=np.float32)

#solution [1,2,3]