# Introduction to numerical algorithms
## Practice class 1 - Python and numpy introduction

### Demo 1: Data types

In [50]:
#numeric
a=1
print(type(a))
b=1.0
print(type(b))
c=1.4+2J
print(type(c))

#string
s="Hello"
print(type(s))

#boolean
d=True
print(type(d))

<class 'int'>
<class 'float'>
<class 'complex'>
<class 'str'>
<class 'bool'>


**Working with integers**

In [51]:
a = 3
b = 5
print(a&b)
print('a + b =', a + b)
print('a * b =', a * b)
print('a**b =', a**b)  #Power
print('a / b =', a / b)  #Division (Note: In Python 2, this would give a different result!)
print('a // b =', a // b)  #Integer Division

1
a + b = 8
a * b = 15
a**b = 243
a / b = 0.6
a // b = 0


**Working with floats**

In [52]:
x = 3.
y = 4. #The dot is important, otherwise it will be an integer 
print('x * y = ', x * y)
print('x**y = ', x**y)
print('x/y = ', x/y)
print('x//y = ', x//y) #Works even for float

x * y =  12.0
x**y =  81.0
x/y =  0.75
x//y =  0.0


**Working with complex numbers**

In [53]:
z1 = 1.+ 2.j
z2 = 2.-1.j
print('z1 + z2 = ', z1 + z2)
print('z1 * z2 = ', z1 * z2)
print('z1 / z2 = ', z1 / z2)
print('z1**z2 = ', z1**z2)  #This also works

#Real part
print(z1.real)
#Imaginary part
print(z1.imag)

z1 + z2 =  (3+1j)
z1 * z2 =  (4+3j)
z1 / z2 =  1j
z1**z2 =  (2.428447747683073+14.93241486964456j)
1.0
2.0


**Working with boolean**

In [54]:
a = True
b = False
print(a)
print(a or b)
print (a and b)
print(not(a))
print(a^b)   # Exclusive OR (XOR)
print(2==a)

True
True
False
False
True
False


**Some fun thing with strings**

In [55]:
s1 = "hello there!"
print(s1[2:5])
s2 = "I want to \nbreak this line"
print(s2)
s3 = """This is going to be a long string, 
and I want to break it into multiple lines."""
print(s3)

llo
I want to 
break this line
This is going to be a long string, 
and I want to break it into multiple lines.


In [56]:
s4 = "Strings can be concatenated " 
s5 ="like this."
s6 = s4 + s5
print(s6)

#can also be repeated
s7 = "This is a string. "
s8 = s7 * 3
print(s8)

Strings can be concatenated like this.
This is a string. This is a string. This is a string. 


#### escape sequences, in details: https://www.python-ds.com/python-3-escape-sequences )
<table border align="center" style="border-collapse: collapse">
  <thead>
    <tr class="tableheader">
      <th align="left"><b>Escape Sequence</b>&nbsp;</th>
      <th align="left"><b>Meaning</b>&nbsp;</th>
    </thead>
  <tbody valign='baseline'>
    <tr><td align="left" valign="baseline"><code>&#92;<var>newline</var></code></td>
        <td align="left">Ignored</td>
    <tr><td align="left" valign="baseline"><code>&#92;&#92;</code></td>
        <td align="left">Backslash (<code>&#92;</code>)</td>
    <tr><td align="left" valign="baseline"><code>&#92;'</code></td>
        <td align="left">Single quote (<code>'</code>)</td>
    <tr><td align="left" valign="baseline"><code>&#92;"</code></td>
        <td align="left">Double quote (<code>"</code>)</td>
    <tr><td align="left" valign="baseline"><code>&#92;a</code></td>
        <td align="left">ASCII Bell (BEL)</td>
    <tr><td align="left" valign="baseline"><code>&#92;b</code></td>
        <td align="left">ASCII Backspace (BS)</td>
    <tr><td align="left" valign="baseline"><code>&#92;f</code></td>
        <td align="left">ASCII Formfeed (FF)</td>
    <tr><td align="left" valign="baseline"><code>&#92;n</code></td>
        <td align="left">ASCII Linefeed (LF)</td>
    <tr><td align="left" valign="baseline"><code>&#92;r</code></td>
        <td align="left">ASCII Carriage Return (CR)</td>
    <tr><td align="left" valign="baseline"><code>&#92;t</code></td>
        <td align="left">ASCII Horizontal Tab (TAB)</td>
    <tr><td align="left" valign="baseline"><code>&#92;v</code></td>
        <td align="left">ASCII Vertical Tab (VT)</td>
    <tr><td align="left" valign="baseline"><code>&#92;<var>ooo</var></code></td>
        <td align="left">ASCII character with octal value <i>ooo</i></td>
    <tr><td align="left" valign="baseline"><code>&#92;x<var>hh...</var></code></td>
        <td align="left">ASCII character with hex value <i>hh...</i></td></tbody>
</table>

In [57]:
print("\tapple\n\"banana\"\\'")

	apple
"banana"\'


how to avoid escape sequencies:

In [58]:
print("a\bpple",r"a\bpple") #r in front of a string means literal
print(r'C:\some\name')

pple a\bpple
C:\some\name


**How to print numbers?**

In [59]:
N = 1500
print("The value of N (=",N,") is greater than allowed (1000)")
print("The value of N (=" + str(N) + ") is greater than allowed (1000)")
print("The value of N (=%d) is greater than allowed (%d)" % (N,1000))
print("The value of N (={}) is greater than allowed ({})".format(N,1000))
print("The value of N (={:.2f}) is greater than allowed ({:.2f})".format(N,1000))
#etc.

The value of N (= 1500 ) is greater than allowed (1000)
The value of N (=1500) is greater than allowed (1000)
The value of N (=1500) is greater than allowed (1000)
The value of N (=1500) is greater than allowed (1000)
The value of N (=1500.00) is greater than allowed (1000.00)


**Collection of data:**
* list: ordered, changeable, and allow duplicate values
* tuple: ordered and unchangeable
* dict: ordered, changeable and do not allow duplicates
* set: unordered, unchangeable, unindexed, doesn't allow duplicates

In [60]:
#list
l = ['apple', 'banana', 'cherry']
print(type(l))
print(len(l))


<class 'list'>
3


In [61]:
#tuple
t = ('apple', 'banana', 'cherry')
print(type(t))
print(len(t))
try:
    t[0] = 'orange'
except Exception as e:
    print("Error:", e)

<class 'tuple'>
3
Error: 'tuple' object does not support item assignment


In [62]:
#dictionary
d = {'name': 'John', 'age': 30, 'city': 'New York'}
print(type(d))
print(len(d))
print(d['name'])

<class 'dict'>
3
John


In [63]:
#set
s = {'apple', 'banana', 'cherry'}
print(type(s))
try:
    s[0] = 'orange'
except Exception as e:
    print("Error:", e)

try:
    print(s[0])
except Exception as e:
    print("Error:", e)

try:
    s.add('apple')
    print(s)
except Exception as e:
    print("Error:", e)

<class 'set'>
Error: 'set' object does not support item assignment
Error: 'set' object is not subscriptable
{'apple', 'cherry', 'banana'}


In [64]:
#Truthiness of different types
print(1==True)
print('a'==True)
print(3==True)
print(1.0==True)
print(1.1==True)

True
False
False
True
False


### Demo 2: Control flow

In [65]:
#different ways to iterate over a list

A=[1,2,3]
for element in A:
    print(element)

for i in range(len(A)):
    print(A[i])

for i,ai in enumerate(A):
    print(i, ai)

1
2
3
1
2
3
0 1
1 2
2 3


In [66]:
#logic
swithch = 1
if (swithch == 1):
    print("Switch is on")
elif (swithch == 0):
    print("Switch is off")
else:
    print("Switch is in an unknown state")

Switch is on


### Demo 3: List comprehensive

In [67]:
A=[1,2,3]
sqA = [ai**2 for ai in A]
print(A)
print(sqA)

[1, 2, 3]
[1, 4, 9]


In [68]:
#one line if-else
switch = 1
state = "on" if swithch == 1 else "off"
print(state)

on


### Demo 4: Indexing

In [ ]:
list = [i for i in range(10)]
list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [70]:
#Zero-based indexing
print(list[0])
print(list[4])

#backward indexing
print(list[-1])
print(list[-4])

#slicing
print(list[0:5])
print(list[5:10])
print(list[0:10:2])
print(list[1:-1:3])

0
4
9
6
[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]
[1, 4, 7]


### Demo 4: Functions

In [71]:
def is_even(a):   
    if a % 2 == 0:
        return True
    else:
        return False
print(is_even(2))
print(is_even(3))
print(is_even(-2))
print(is_even(-3))

True
False
True
False


the `lambda` function

In [72]:
is_even = lambda a: a % 2 == 0
print(is_even(2))
print(is_even(3))
print(is_even(-2))
print(is_even(-3))

True
False
True
False


### Numpy, a very brief intro

In [73]:
# Uncomment the following line to install numpy if you haven't already
# !pip install numpy

import numpy as np

In [74]:
#vectors and matrices stored in numpy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
A = np.array([[1, 2, 3], [4, 5, 6]])

# elementwise operations
print(a+b)
print(a-b)
print(a/b)
print(a**2)

# what is it?
# Spoiler: not the matrix product
print(a*a)
print(A*A)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[1 4 9]
[1 4 9]
[[ 1  4  9]
 [16 25 36]]


In [75]:
# The real matrix product is done with the @ operator
print(a@a)  
print(A@a)
print(A@A.T)  #A.T is the transpose of A

14
[14 32]
[[14 32]
 [32 77]]


In [76]:

#indexing as before
print(a[0])
print(A[0, 0])

#also slicing as before
print(a[0:2])
print(A[0:2, 0:2])

#particularly useful for matrices: slicing with a single index
print(A[0])  #first row
print(A[:, 0])  #first column

1
1
[1 2]
[[1 2]
 [4 5]]
[1 2 3]
[1 4]


In [77]:
#universal functions
print(np.sqrt(2))
print(np.sin(np.pi/2))
print(np.log(10))

1.4142135623730951
1.0
2.302585092994046


**Note that they are vectorized and works very efficiently with numpy arrays!**

<span style="color:red">Be careful, always use functions from only one package, numpy is higly recommended!</span>

Avoid the parallel use of e.g. numpy and math  

### Warmup task
1. Create a list containing the square of the first 10 odd numbers.
2. Create a dictionary with two lists containing the odd and the even numbers.


In [16]:
# 1.
list = []
for j in range(20):
    if j % 2 != 0:
        list.append(j**2)
list

# or

odd = [i**2 for i in range(1, 20, 2)]
print(odd)

# odd = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

# 2.
dih = {'even': [i for i in range(0, 20, 2)], 'odd': [i for i in range(1, 20, 2)]}
print(dih['even'])
print(dih['odd'])

[1, 9, 25, 49, 81, 121, 169, 225, 289, 361]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


### Task 1
Write a function that finds the minimum in a list!

In [17]:
def find_min(l):
    min = l[0]
    for i in range(len(l)):
        if l[i] < min:
            min = l[i]
    return min
print(find_min([-7,-6,4,5,-6,4,-8,6,-5]))

-8


### Task
[Harry Potter books](https://github.com/amephraim/nlp)

Your task will be to analyize the words in Harry Potter and The Sorcerer's Stone.

Download the Harry Potter books from the provided link. Then read in the text of the first book.
1. Split the text to words. Take care of special characters like ,?!" etc. and capital letters.
2. How many different words are in the book? Use set!
3. What are the ten most common words? Use dictionary to story the word counts.

In [7]:
# Got help mostly from StackExchange discussions and friends.
with open("C:\\VSCode\\Introduction to Numerical Algorithms\\Practice\\Week 1\\J. K. Rowling - Harry Potter 1 - Sorcerer's Stone.txt") as file:
    str = file.read().lower()
spt = ""
for i in str:
    if i.isalnum():
        spt += i
    else: 
        spt += " "
total = spt.split()
unique = set(total)
print(f"The total number of words in the text is {len(total)}.")
print(f"The total number of unique words in the text is {len(unique)}.")

# Help was needed from one of my classmates.
top = {}
for word in total:
    top[word] = top.get(word, 0) + 1
sorting = sorted(top.items(), key = lambda item: item[1], reverse = True)[:10]
for word, count in sorting:
    print(f"The word '{word}' was mentioned {count} times.")

The total number of words in the text is 80648.
The total number of unique words in the text is 5777.
The word 'the' was mentioned 3630 times.
The word 'and' was mentioned 1924 times.
The word 'to' was mentioned 1861 times.
The word 'he' was mentioned 1758 times.
The word 'a' was mentioned 1691 times.
The word 'harry' was mentioned 1327 times.
The word 'of' was mentioned 1267 times.
The word 'was' was mentioned 1186 times.
The word 'it' was mentioned 1185 times.
The word 'you' was mentioned 1035 times.
